### PR TITLE
feat: add a Node.js metacontroller template

### PR DESCRIPTION
**Pull request by lance**
# Changes

- 🎁  Adds a metacontroller function template in Node.js

The [Metacontroller](https://metacontroller.github.io/metacontroller/intro.html) project makes it easy to create and deploy controllers to manage custom resources, or to decorate existing managed resources with additional objects. This template is a Node.js function which uses the Metacontroller API to decorate all Knative functions with a default `Trigger` for all deployed functions. The `Trigger` is created or recreated for each update of the function.

This template is, as are most templates, a starting point. Users are encouraged to use this example to create Metacontrollers managing all kinds of Kubernetes API objects.

/kind enhancement

## Work in progress

- [x] Update README.md to explain everything step-by-step with links to metacontroller and other docs
- [x] Fix tests - they are still the basic tests from a `func` generated Node.js function
- [x] Remove `func.yaml` from the project since this is meant to be a template
- [ ] ~Add `manifest.yaml` if necessary~

Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/1120

Signed-off-by: Lance Ball <lball@redhat.com>

/cc @salaboy wdyt?

### CODE REVIEW

**Comment by rhuss** [comment]
So for my ignorance, but is this somewhat similar to https://metacontroller.github.io/metacontroller/ ?

**Comment by lance** [comment]
@rhuss this is an implementation of Metacontroller.

**Comment by lance** [comment]
Closing and re-opening to see if I can get prow to behave better

**Pull request merged**
