### PR TITLE
Fix gofmt and goimports errors in CI

### PR DESCRIPTION
**Pull request by daisy-ycguo**
# Changes

- :broom: Fix gofmt and goimports errors in CI auto checks

### CODE REVIEW

**Comment by daisy-ycguo** [comment]
The unit test error is because that this project is not a golang project and there is no main module. I think we shall remove or disable the unit test.

**Comment by matejvasek** [comment]
/lgtm
Thanks!

**Comment by matejvasek** [comment]
@lance can you override the test please?

**Comment by lance** [comment]
FYI https://github.com/knative-sandbox/knobots/pull/235

**Comment by lance** [comment]
Closing and reopening to see if that will help with merge status

**Comment by lance** [comment]
/override test / Unit Tests
🤷

**Comment by lance** [comment]
@daisy-ycguo can you rebase with main? It removes the knative github actions and should result in these checks being no longer required.

**Comment by upodroid** [comment]
I'm looking at the override plugin code and I might have identified a bug.

**Comment by daisy-ycguo** [comment]
> @daisy-ycguo can you rebase with main? It removes the knative github actions and should result in these checks being no longer required.

I've rebased. It looks like all github actions are disabled.

**Comment by lance** [comment]
/lgtm
/approve
Thanks @daisy-ycguo !

**Pull request merged**
